### ISSUE TITLE
Unable to start Stream Registry

### ISSUE THREAD

**Issue by kknhalo** [ExpediaGroup/stream-registry#239]
# Expected Behavior

After checking out the master branch, I should be able to build and run the project.

# Actual Behavior

When trying to run the project I get this: 
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/user/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

# Steps to Reproduce

Running the project is not described in the user guide, I used what I know:
./mvnw clean package # this step is provided in the guide
./mvnw spring-boot:run # not part of the guide

# Additional Information

While looking at the documentation I found this: https://expediagroup.github.io/stream-registry/usage/
According to that article I should be able to build the project and a docker image using make. I was not able to find Makefile anywhere in the project (master branch)

**Comment by OneCricketeer** [comment]
Hi @kknhalo the docs are not being maintained... 

#219
